spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://dut-we.h.filess.io:3307/?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=10000&socketTimeout=30000}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ktltweb_becamering}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:3160bc4eae75cb3a801c101972db2b4ed8feda07}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-init-sql=USE ` ktltweb_becamering`
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.initialization-fail-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

springdoc.pathsToMatch=/api/**
server.port=${PORT:8081}
server.address=0.0.0.0
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
